# .github/workflows/commitlint.yml
name: Lint Commits

permissions:
  contents: read

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install depends
        run: npm install

      - name: Validate commitlint
        if: github.event_name == 'push'
        run: |
          git log -1 --pretty=%B | npx commitlint

      - name: Validate pull request commits
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=100
          npx commitlint --from=origin/${{ github.base_ref }} --to=HEAD --verbose
